# Generated by Django 6.0.3 on 2026-05-01 03:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elon', '0003_comment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='elon',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_elons', to=settings.AUTH_USER_MODEL),
        ),
    ]
