# Generated by Django 6.0.3 on 2026-05-03 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elon', '0004_elon_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('birth_year', models.PositiveIntegerField()),
                ('died_year', models.PositiveIntegerField(blank=True, help_text='Tirik bolsa yil kiritmang', null=True)),
                ('mild', models.CharField(choices=[('mild_a', 'millodan avvalgi'), ('mild', 'millodiy')], default='mild')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='elon',
            name='author',
            field=models.ManyToManyField(related_name='elons', to='elon.author'),
        ),
        migrations.AddField(
            model_name='elon',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elon.publisher'),
        ),
    ]
